'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
const COLS=316,ROWS=317,COUNT=100000;
const tiers=[['EDGE',50],['OUTER',80],['INNER',120],['PREMIUM',200],['CENTER',500],['GOLDEN',2000]];
const packages=[['START',5,250],['BUSINESS',25,1750],['PRO',100,6500],['PREMIUM',500,27500],['BIG BRAND',2000,100000]];
function priceFor(i){const r=Math.floor(i/COLS),c=i%COLS;const d=Math.min(r,ROWS-1-r,c,COLS-1-c);return d<8?2000:d<20?500:d<45?200:d<90?120:d<145?80:50}
function fmt(n){return n.toLocaleString('cs-CZ')+' Kč'}
export default function Home(){
 const [selected,setSelected]=useState([]),[open,setOpen]=useState(false),[file,setFile]=useState(null),[name,setName]=useState(''),[email,setEmail]=useState(''),[message,setMessage]=useState(''),[notice,setNotice]=useState(''),[filled,setFilled]=useState(0),[sold,setSold]=useState(new Set()),[reserved,setReserved]=useState(new Set()),[loading,setLoading]=useState(true);
 const canvas=useRef(null);
 const total=useMemo(()=>selected.reduce((s,i)=>s+priceFor(i),0),[selected]);
 async function refresh(){try{const r=await fetch('/api/cells',{cache:'no-store'});const d=await r.json();const s=new Set(d.sold||[]),rv=new Set(d.reserved||[]);setSold(s);setReserved(rv);setFilled(s.size)}catch(e){console.error(e)}finally{setLoading(false)}}
 useEffect(()=>{refresh();const t=setInterval(refresh,15000);return()=>clearInterval(t)},[]);
 useEffect(()=>{draw()},[selected,sold,reserved]);
 function draw(){const c=canvas.current;if(!c)return;const ctx=c.getContext('2d');const w=c.width,h=c.height,sx=w/COLS,sy=h/ROWS,chosen=new Set(selected);ctx.fillStyle='#17171c';ctx.fillRect(0,0,w,h);for(let i=0;i<COUNT;i++){const r=Math.floor(i/COLS),col=i%COLS,p=priceFor(i);ctx.fillStyle=sold.has(i)?'#09090b':reserved.has(i)?'#77777e':chosen.has(i)?'#fff':p>=2000?'#555':p>=500?'#39393f':p>=200?'#29292e':'#202025';ctx.fillRect(col*sx,r*sy,Math.max(1,sx-.25),Math.max(1,sy-.25))}}
 function toggle(e){const rect=e.currentTarget.getBoundingClientRect(),x=(e.clientX-rect.left)*(e.currentTarget.width/rect.width),y=(e.clientY-rect.top)*(e.currentTarget.height/rect.height),c=Math.max(0,Math.min(COLS-1,Math.floor(x/(e.currentTarget.width/COLS)))),r=Math.max(0,Math.min(ROWS-1,Math.floor(y/(e.currentTarget.height/ROWS)))),i=Math.min(COUNT-1,r*COLS+c);if(sold.has(i)||reserved.has(i))return;setSelected(s=>s.includes(i)?s.filter(x=>x!==i):[...s,i])}
 function packagePick(n){const set=new Set(selected),arr=[...selected];for(let i=0;i<COUNT&&arr.length<n;i++)if(!set.has(i)&&!sold.has(i)&&!reserved.has(i)){set.add(i);arr.push(i)}setSelected(arr);document.getElementById('mosaic')?.scrollIntoView({behavior:'smooth'})}
 function upload(e){const f=e.target.files?.[0];if(!f)return;if(f.size>2*1024*1024){setNotice('Soubor může mít maximálně 2 MB.');return}const reader=new FileReader();reader.onload=()=>setFile(reader.result);reader.readAsDataURL(f)}
 async function submit(){if(!selected.length)return;if(!name||!email){setNotice('Vyplň jméno a e-mail.');return}setNotice('Rezervuji vybraná pole…');try{const r=await fetch('/api/checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({cellIds:selected,name,email,message,imageData:file})});const d=await r.json();if(!r.ok){setNotice(d.error||'Checkout se nepodařilo vytvořit.');await refresh();return}window.location.href=d.url}catch(e){setNotice('Nepodařilo se spojit s platbou. Zkus to znovu.')}}
 return <main>
 <header><button className="brand" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})}>100K<span>●</span></button><nav><button onClick={()=>document.getElementById('mosaic')?.scrollIntoView({behavior:'smooth'})}>MOZAIKA</button><button onClick={()=>document.getElementById('how')?.scrollIntoView({behavior:'smooth'})}>JAK TO FUNGUJE</button><button onClick={()=>document.getElementById('cause')?.scrollIntoView({behavior:'smooth'})}>DOBRÁ VĚC</button></nav><button className="cta" onClick={()=>document.getElementById('mosaic')?.scrollIntoView({behavior:'smooth'})}>KUP SVÉ POLE</button></header>
 <section className="hero"><div><p className="eyebrow">100 000 POLÍ • 1 OBRAZ • 1 DOBRÁ VĚC</p><h1>Buď součástí<br/><i>něčeho velkého.</i></h1><p className="lead">Vyber si vlastní místo v obrovské veřejné mozaice. Nahraj fotku, logo nebo vzkaz. Každý nákup zůstane součástí výsledného obrazu.</p><div className="hero-actions"><button className="primary" onClick={()=>document.getElementById('mosaic')?.scrollIntoView({behavior:'smooth'})}>VYBRAT POLE →</button><button className="ghost" onClick={()=>document.getElementById('how')?.scrollIntoView({behavior:'smooth'})}>Jak to funguje</button></div><div className="stats"><div><b>100 000</b><span>CELKEM POLÍ</span></div><div><b>{filled.toLocaleString('cs-CZ')}</b><span>PRODÁNO</span></div><div><b>{((filled/COUNT)*100).toFixed(1).replace('.',',')} %</b><span>ZAPLNĚNO</span></div></div></div><div className="hero-card"><div className="mini-grid">{Array.from({length:400},(_,i)=><span key={i} className={i%17===0?'lit':''}/>)}</div><strong>Jeden obraz.</strong><small>Tisíce lidí. Jeden společný příběh.</small><div className="progress"><i style={{width:`${Math.min(100,(filled/COUNT)*100)}%`}}/></div></div></section>
 <section id="mosaic" className="workspace"><div className="section-head"><div><p className="eyebrow">INTERAKTIVNÍ MOZAIKA</p><h2>Vyber si přesné místo.</h2><p className="sub">Klikni do mozaiky. Střed je vzácnější, okraj dostupnější.</p></div><div className="legend">{tiers.map(([n,p])=><span key={n}><i className={n.toLowerCase()}/>{n} {fmt(p)}</span>)}</div></div><div className="mosaic-layout"><div className="mosaic-wrap"><canvas ref={canvas} width="948" height="951" onClick={toggle} aria-label="Interaktivní mozaika"/><div className="zoom-note">{loading?'Načítám stav polí…':'100 000 polí · klikni pro výběr'}</div></div><aside><p className="eyebrow">TVŮJ VÝBĚR</p><h3>{selected.length} <small>{selected.length===1?'pole':'polí'}</small></h3><div className="sum">{fmt(total)}</div><div className="selection-list">{selected.length?selected.slice(-8).map(i=><span key={i}>#{i+1} · {fmt(priceFor(i))}</span>):<span>Nemáš zatím vybrané žádné pole.</span>}</div>{selected.length>8&&<small>+ {selected.length-8} dalších</small>}<button className="pay" disabled={!selected.length} onClick={()=>setOpen(true)}>POKRAČOVAT →</button><button className="clear" disabled={!selected.length} onClick={()=>setSelected([])}>Zrušit výběr</button><small>Rezervace se vytvoří až při pokračování k platbě.</small></aside></div></section>
 <section id="how" className="how"><div><p className="eyebrow">JEDNODUCHÉ 4 KROKY</p><h2>Od výběru k obrazu.</h2></div><div className="steps">{[['01','Vyber','Klikni na libovolná dostupná pole v mozaice.'],['02','Nahraj','Přidej fotku, logo nebo vlastní vzkaz.'],['03','Zaplať','Bezpečná platba proběhne přes Stripe Checkout.'],['04','Staň se součástí','Po zaplacení zůstanou tvoje pole součástí výsledného obrazu.']].map(x=><div className="step" key={x[0]}><b>{x[0]}</b><strong>{x[1]}</strong><p>{x[2]}</p></div>)}</div></section>
 <section id="cause" className="cause"><div><p className="eyebrow">DOBRÁ VĚC</p><h2>Projekt s veřejným přesahem.</h2><p>Na webu bude před spuštěním prodeje jasně uvedeno, kam peníze směřují, jaký je právní subjekt projektu a jak bude zveřejňováno využití prostředků.</p></div><div className="cause-card"><strong>100K</strong><span>Transparentní projekt</span><small>Konkrétní příjemce a pravidla budou doplněny před ostrým spuštěním plateb.</small></div></section>
 <section className="packages"><p className="eyebrow">PRO FIRMY I JEDNOTLIVCE</p><h2>Chceš větší prostor?</h2><div className="cards">{packages.map(([n,c,p])=><div className="card" key={n}><small>{n}</small><b>{c.toLocaleString('cs-CZ')} polí</b><strong>{fmt(p)}</strong><button onClick={()=>packagePick(c)}>VYBRAT →</button></div>)}</div></section>
 <section className="leader"><div><p className="eyebrow">KDO UŽ JE UVNITŘ</p><h2>Podporovatelé</h2></div><div className="leaderboard"><div><span>01</span><b>První podporovatel</b><em>—</em></div><div><span>02</span><b>Brzy zde bude tvoje jméno</b><em>—</em></div><div><span>03</span><b>Brzy zde bude tvoje značka</b><em>—</em></div></div></section>
 <footer><div className="brand">100K<span>●</span></div><p>100 000 lidí. 1 obraz. 1 dobrá věc.</p><p className="muted">Transparentnost · Kontakt · Podmínky · Ochrana osobních údajů</p></footer>
 {open&&<div className="modal-backdrop" onClick={()=>setOpen(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setOpen(false)}>×</button><p className="eyebrow">DALŠÍ KROK</p><h2>Dokonči svůj vstup.</h2><p className="modal-total">{selected.length} polí · <b>{fmt(total)}</b></p><label>Jméno / název<input value={name} onChange={e=>setName(e.target.value)} placeholder="Jan Novák / Firma s.r.o."/></label><label>E-mail<input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="vas@email.cz"/></label><label>Fotka nebo logo<input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload}/></label>{file&&<img className="upload-preview" src={file} alt="Náhled nahraného souboru"/>}<label>Vzkaz <textarea value={message} onChange={e=>setMessage(e.target.value)} maxLength={180} placeholder="Krátký vzkaz (volitelné)"/></label><button className="pay big" onClick={submit}>POKRAČOVAT K PLATBĚ →</button>{notice&&<div className="notice">{notice}</div>}<small>Vybraná pole se při zahájení platby rezervují na 30 minut.</small></div></div>}
 </main>
}